apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-java-app1.name" . }}
  labels:
    {{- include "my-java-app1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "my-java-app1.selectorLabels" . | nindent 4 }}